### ISSUE TITLE
OFFIX 1.0 ROADMAP

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#303]
## Roadmap

The roadmap is still in progress

- [x] New React example app based on Offix + Graphback #324 
- [x] React Native Example App
- [ ] General bugfixing and stabilizing the API
- [ ] Apollo 3.0 #222 
- [ ] URQL enablement #235 
- [ ] Stabilise storage implementation #325
- [ ] Improve Docs and Landing Page

**Comment by wtrocki** [comment]
@darahayes let's add additional items you would see us to execute

**Comment by darahayes** [comment]
I'm +1 on the URQL enablement. By integrating another GraphQL client we will improve and solidify the scheduler implementation and it will provide additional choice for users and it derisks our dependence on Apollo.

I'm also +1 for Apollo 3.0, this is obvious.

I have two additional items I'd like to add. Tl;DR

1. A new more maintainable showcase app using Offix + Graphback together
2. Solidify the persistence/storage layer

## A new showcase app based on Offix + Graphback working together

The showcase app historically was built to demonstrate use cases coming from several 3rd party services. As a result, the GraphQL client and server implementations are there but with a bunch of additional baggage.

The way the client is being used is also based on how the client historically worked in much earlier versions. Even though Offix has matured a lot, the current showcase has not evolved alongside the newer versions and features of the client.

As part of having Offix 1.0 I think it's important that we provide a sample application or a set of small applications that demonstrate Offix + Graphback working together. Ideally this is what I'd like

* A sample app or a set of small sample apps that demonstrate various use cases of Offix.
* I think we should power the server side using Graphback. This will help us start converging Offix + Graphback together.
* Ideally the app (or apps) will be small enough that they are much easier to understand by end users and they are much more maintainable for us as a team.
* Ideally we will capitalise on the demand for react (regardless of what framework you like to use, React _seems_ to be the leading choice in the community)

## Solidify The Storage

We've had lots of issues around storage.

https://github.com/aerogear/offix/issues/187
https://github.com/aerogear/offix/issues/218
https://github.com/aerogear/offix/issues/171
https://github.com/aerogear/offix/issues/160

I think we need to review the storage mechanism we have right now and make a decision about a couple of things.

* Do we stick with idb-localstorage and improve it or do we move to some other provider (example: Dexie)?
* Do we build a comprehensive mechanism for migrating the storage if the format changes?

**Comment by darahayes** [comment]
I think we should add more comprehensive React Native support for 1.0.

Right now, there is some support but it's not very comprehensive. Users are using some code snippets/hacks to get cache/storage/networking working. I think for version 1 we need to evaluate the state of Offix within react native and see what could be improved.

We might take those code snippets and turn them into packages that are tested and maintained. If we don't have enough time/resources for that, we could at least provide some better documentation. 

Pinging @mmusil because the react native example app you're working on is related. If you have any input on this it would be great.

**Comment by wtrocki** [comment]
+1 on having some general issue around it and we can come with the plan together with the @mmusil

**Comment by wtrocki** [comment]
Closing. We going to use milestones to manage roadmaps from now
